version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning
    ports:
      - "3000:3000"
  app-a:
    build: ./app
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=app-a
    depends_on:
      - prometheus
      - tempo
      - loki
  app-b:
    build: ./app
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=app-b
    depends_on:
      - prometheus
      - tempo
      - loki
