services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./etc/tempo/tempo.yml:/etc/tempo.yml
    command: ["-config.file=/etc/tempo.yml"]
    ports:
      - "3200:3200"   # UI
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # HTTP/JSON OTLP（如果要用 HTTP）

  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

  app-a:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: observability-demo-app
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=app-a
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - tempo
      - loki

  app-b:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: observability-demo-app
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=app-b
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    ports:
      - "8081:8081"
    depends_on:
      - prometheus
      - tempo
      - loki
