global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-a'
    static_configs:
      - targets: ['app-a:8080']
        labels:
          service: 'app-a'

  - job_name: 'app-b'
    static_configs:
      - targets: ['app-b:8081']
        labels:
          service: 'app-b'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
